AWSTemplateFormatVersion: "2010-09-09"
Description: EndPoint

#-------------------------------------------------------------------
#Create Endpoint
#-------------------------------------------------------------------
Resources:
  EndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EndpointSecurityGroup
      GroupName: EndpointSecurityGroup
      VpcId: { "Fn::ImportValue": !Sub "#VPC 입력" }
      Tags:
        - Key: Name
          Value: EndpointSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: #VPCCIDR 입력
  EndpointSSM:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref EndpointSecurityGroup
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      SubnetIds:
        - { "Fn::ImportValue": !Sub "# subnet-a 입력" }
        - { "Fn::ImportValue": !Sub "# subnet-c 입력" }
      VpcEndpointType: Interface
      VpcId: { "Fn::ImportValue": !Sub "#VPC 입력" }
  EndpointSSMMessages:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref EndpointSecurityGroup
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssmmessages
      SubnetIds:
        - { "Fn::ImportValue": !Sub "# subnet-a 입력" }
        - { "Fn::ImportValue": !Sub "# subnet-c 입력" }
      VpcEndpointType: Interface
      VpcId: { "Fn::ImportValue": !Sub "#VPC 입력" }
  EndpointEC2Messages:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref EndpointSecurityGroup
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ec2messages
      SubnetIds:
        - { "Fn::ImportValue": !Sub "# subnet-a 입력" }
        - { "Fn::ImportValue": !Sub "# subnet-c 입력" }
      VpcEndpointType: Interface
      VpcId: { "Fn::ImportValue": !Sub "#VPC 입력" }

#-------------------------------------------------------------------
#OutPut
#-------------------------------------------------------------------
Outputs:
  SecurityGroup:
    Value: !Ref EndpointSecurityGroup
    Export:
      Name: !Sub "endpoint-sg"
  EndpointSSM:
    Value: !Ref EndpointSSM
    Export:
      Name: !Sub "endpoint-ssm"
  EndpointSSMMessages:
    Value: !Ref EndpointSSMMessages
    Export:
      Name: !Sub "endpoint-ssmmessages"
  EndpointEC2Messages:
    Value: !Ref EndpointEC2Messages
    Export:
      Name: !Sub "endpoint-ec2messages"